name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
#        java-version: 1.8
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Unit Tests
      run: bash ./gradlew test --stacktrace

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Build debug APK
        run: bash ./gradlew clean assembleDebug --stacktrace
      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        with:
          tag_name: ${{ env.VERSION_TAG }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: Android ${{ env.VERSION_TAG }}
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Upload APK
#        uses: actions/upload-artifact@v3
#        with:
#          name: app
#          path: app/build/outputs/apk/debug/app-debug.apk
