name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.10.0
      with:
          access_token: ${{ github.token }}
          all_but_latest: true
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: adopt
    - name: Unit Tests
      run: bash ./gradlew test --stacktrace

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
      - name: Build debug APK
        run: bash ./gradlew clean assembleDebug --stacktrace
      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.2
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: Android.apk
#          asset_content_type: application/zip
